### ISSUE TITLE
Provide a basic documentation to build the project

### ISSUE THREAD

**Issue by louison** [charleywright/spotify-analyze-v2#1]
Hi there, I'm trying to build your project on Linux and I get the following error when executing `cmake --build .`:

```
In file included from /home/lou/spotify-analyze-v2/needle/src/events/events.hpp:5,
                 from /home/lou/spotify-analyze-v2/needle/src/events/event_service.cpp:1:
/home/lou/spotify-analyze-v2/needle/src/mercury/mercury.hpp:11:10: fatal error: hermes_mercury/mercury.old.pb.h: No such file or directory
   11 | #include "hermes_mercury/mercury.old.pb.h"
```

Can you provide a basic tutorial on how to build it from scratch please ? 

Thank you in advance for your work :)

**Comment by charleywright** [comment]
I started working on the injector branch a few months back, but never got around to merging it into master. I'll see if I can finish it off tonight

**Comment by charleywright** [comment]
Documentation should be a lot more useful now, and I merged the injector branch into master so everything is up to date. Let me know if you have any suggestions or issues

**Comment by superboum** [comment]
Hi @charleywright, needle works fine on NixOS but fails to compile in an Ubuntu docker container. 
This is due to a weird interaction between:
  - your call to `protobuf_generate` + your repo structure (having a `proto` folder that does not exist when you call your include).
  - and the patched/outdated version of the `protubuf-generate.cmake` file that Ubuntu ships, that is different from the [upstream one](https://github.com/protocolbuffers/protobuf/blob/main/cmake/protobuf-generate.cmake)

The cmake file of the Ubuntu package always add `-I ${CMAKE_CURRENT_SOURCE_DIR}` to the `protoc` args, even if you specify `IMPORT_DIRS` while the upstream `protobuf-generate.cmake` adds this option only if `IMPORT_DIRS` is not defined.

It results in a call that looks like: `protoc ... -I spotify-analyze-v2/needle -I spotify-analyze-v2/needle/proto ...`, that in turns, results in a wrong folder structure in the `build` folder (`build/proto/proto/...`) which explains why cmake can't resolve the import. There is no easy way to fix that problem, but I am working on a workaround at least.

**Comment by superboum** [comment]
I was able to compile Needle on Ubuntu by manually compiling Protobuf:

```Dockerfile
FROM ubuntu:23.04

RUN apt-get update && apt-get install -y git build-essential cmake

WORKDIR /root
RUN git clone --recurse --branch v21.12 https://github.com/protocolbuffers/protobuf.git

WORKDIR /root/protobuf
RUN cmake -B build/ -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_SHARED_LIBS=ON -Dprotobuf_BUILD_TESTS=OFF
RUN cmake --build build --config Release -j $(nproc)
RUN cmake --build build --config Release --target install

WORKDIR /root
RUN git clone  --depth=1 https://github.com/charleywright/spotify-analyze-v2.git

WORKDIR /root/spotify-analyze-v2/needle
RUN cmake -B build/ -DCMAKE_BUILD_TYPE=Release -DProtobuf_DIR=/usr/local/lib/cmake/protobuf/
RUN cmake --build build --config Release -j $(nproc)
```

Some important points:
  - `protobuf_BUILD_SHARED_LIBS` might or might not be required
  - But `--branch v21.12` is very important, as compiling against `HEAD` of the `main` branch currently throws a relocation error.

The relocation error on branch `main` is similar to the one from this issue: https://github.com/protocolbuffers/protobuf/issues/11467

```
/usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E' can not be used when making a shared object
/usr/bin/ld: failed to set dynamic section sizes: bad value
```

**Comment by charleywright** [comment]
I recall having a lot of problems getting libprotobuf to statically link on Windows and ended up giving up because I rarely use windows. That does mean on windows the libprobufd.dll file needs to be copied into the Spotify directory or its location included in your library search paths. Hopefully I'll get around to fixing this soon but if someone who knows cmake better than me wants to submit a PR I'd be very open to that.

The consequence of this is libprotobuf is linked as a shared library which is not ideal when injecting into a process

**Comment by superboum** [comment]
Unfortunately I am a Linux user for many years now: I have no experience/knowledge on Windows. 
Still, thanks for your time and explanations. :-)

**Comment by charleywright** [comment]
I just merged the major rewrite I've been working on so this problem no longer exists and I am comfortable closing this. The new documentation should be sufficient however any suggestions or improvements are always welcome
